### ISSUE TITLE
piskel json to amethyst ron spritesheet converter.

### ISSUE THREAD

**Issue by yaahallo** [yaahallo/gameoff#17]
Right now the open source tool that paige is using to make sprites outputs json spritesheets that are similar to what is expected by amethyst, but not quite good enough.

Editing these things by hand would be super annoying, so we're going to write a really simple converter to read the piskel format and output the amethyst format, should be just a couple of lines of serde code.

Marbin is working on it I think.

**Comment by Chibin** [comment]
Correction @yaahallo worked on it :)
